name: agrisoft
description: "AgriSoft by Evolvix Enterprise - Aplicación moderna para gestión agrícola integral"
publish_to: 'none'
homepage: https://evolvix-ent.github.io/agrisoft
repository: https://github.com/evolvix-ent/agrisoft

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.5.6
  
  # UI y navegación
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  
  # Estado y utilidades
  flutter_riverpod: ^2.4.9
  
  # Fechas y tiempo
  intl: ^0.20.2

  # Base de datos local (offline)
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3

  # Conectividad
  connectivity_plus: ^5.0.2

  # Almacenamiento local
  shared_preferences: ^2.2.2
  
  # HTTP y APIs
  http: ^1.1.0
  
  # Utilidades
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Generación de código
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
